name: Build HPY Soft-Engine

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore hpy-winforms/HPYSoftEngine/HPYSoftEngine.csproj
      - name: Publish
        run: dotnet publish hpy-winforms/HPYSoftEngine/HPYSoftEngine.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:EnableCompressionInSingleFile=true -o ./output
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: HPY-Soft-Engine
          path: ./output/HPY-Soft-Engine.exe
